### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by GoneUp** [GoneUp/GPK_RePack#1]
- Rename Classes -> Model
- Finally add graphic import/export

**Comment by Owyn** [comment]
- view DDS graphics in the program
- export\import DDS graphic files and not just raw data

please ^_^

**Comment by GoneUp** [comment]
Problems with UtHelper? :D

**Comment by Owyn** [comment]
yea, just stumbled across a file from other modder uthelper corrupts when trying to change class icons so it crashes the game when raid group uses docking feature while dragging groups, 

but I could finally do it with TeraHelper fine (but in a kinda complex way via replacing rawdata), 

and he modded greyscale PF_A8R8G8B8 somehow also which uthelper doesn't work with(PartyWindowRaidInfo_I1), so I was hoping that we could just use TeraHelper in future to get everything done :

[S1UI_PartyWindowRaidInfo.zip](https://github.com/GoneUp/GPK_RePack/files/1036913/S1UI_PartyWindowRaidInfo.zip)

**Comment by GoneUp** [comment]
Okay, thanks for the info. Working on it.

Also todo:

- add a simple object search feature
