### ISSUE TITLE
Is it possible to update for 64bit client?

### ISSUE THREAD

**Issue by AAGom** [GoneUp/GPK_RePack#5]
Hello.
I was poor at English and used the machine.
Thank you for creating a good tool.
Tera Korea server (KTera) cannot use Terahelper with 64bit update recently.

Is it possible to update for 64bit client?

**Comment by GoneUp** [comment]
Hello AAGom
Thanks for reporting, I will take a look and hopefully add support.

**Comment by GoneUp** [comment]
https://github.com/GoneUp/GPK_RePack/releases/tag/v0.15 was released with a initial support for x64.
