### ISSUE TITLE
Mass extraction of images.

### ISSUE THREAD

**Issue by Icoss** [GoneUp/GPK_RePack#7]
Hi!
Is it possible to add a function of mass extraction of images from the paks? Or maybe it's there already and I just didn't noticed it?

**Comment by GoneUp** [comment]
It's there for the new Composite GPKs. In the menu Composite GPK -> Dump Textures. I would advise to do it in smaller batches (max 25 gpks) because it's really a lot of textures and the program runs into memory issues. Or do you mean extraction on general gpks?

**Comment by Icoss** [comment]
Thank you very much for the answer! I've had an older build, which didn't had that menu option. Updated it and that's exactly, what I was looking for!

P.S. Sorry for the late reply. Looks like email notifications are not working for me here.

**Comment by GoneUp** [comment]
Perfect that it helped you. I will maybe add it also for normal gpks.
